server: 
  port: 8090
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    com.example.demo: DEBUG
spring: 
  application: 
    name: salary-service
  datasource:
    initialization-mode: always
    url: jdbc:mysql://localhost:3306/EmployeeDB?useSSL=false
    username: root
    password: arpa9674
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
eureka: 
  registration: 
    enabled: true
  client: 
    region: default
    registryFetchIntervalSeconds: 50